function dd_store_output(array,title,taskdir)

T = array2table(array);

T.Properties.VariableNames = {'country','tdur',...
                              'vlyl_1','vlyl_2','vlyl_3','vlyl_4', ...
                              'gdpl_1','gdpl_2','gdpl_3','gdpl_4','gdpl_5','gdpl_6','gdpl_7','gdpl_8','gdpl_9','gdpl_10', ...
                              'vsyl', ...
                              'fsiz_1','fsiz_2','fsiz_3','fsiz_4', ...
                              'chad_1','chad_2','chad_3','chad_4', ...
                              'mort_1','mort_2','mort_3','mort_4', ...
                              'hpeak','hbdays','hbdoc', ...
                              'wdunem','numldn','elimok','timldn'};

writetable(T,strcat(taskdir,title,'.csv'));

end